### ISSUE TITLE
Search Functionality Failing to Work Intermittently

### ISSUE THREAD

**Issue by Devurauxe** [Oracle-of-the-Void/ootv-client#170]
Today on 10/5/2024, the search functionality for the website has been failing to work on occasion, with the loading icon spinning until a message comes up stating "something went wrong with the search".

Reproduction steps:
- Search for a card with any search terms
- Note the failure for the database to retrieve results

This seems to occur for 10-20 minutes at a time and the site will occasionally start working again. Thank you so much for you continuing to support this game and updating the website.

![image](https://github.com/user-attachments/assets/2e1a346b-0e93-43b8-b33a-e0532a6b41a9)

**Comment by Devurauxe** [comment]
From looking at the backend through inspect element, the fetch cards function is getting a #502 bad gateway error, and two other functions (update log table and attributes) are getting #503 service issue. it's possible the amazon server it's running on is encountering issues.

**Comment by ksuquix** [comment]
I can't get a failure.     I'll force opensearch to migrate... I needed to move it to t3 instances instead of t2 anyway.   Everything else is using cloudfront/lambda/dynamodb, so it shouldn't be possible to have an outage unless there is a larger aws outage.  Let me know if you see a change in the next little bit.  (not sure how long it takes to migrate opensearch services)

**Comment by Devurauxe** [comment]
If the search functionality ends up failing again, I will post a comment today with timestamp screenshots on inspect, but it seems to be working just fine so far
